variables:
  IMAGE_NAME: expensenest
services:
  - name: docker:dind
cache:
 paths:
  - .m2/repository

stages:
  - maven_build
  - docker_build
  - deploy

maven_build:
  image: openjdk:20-jdk
  stage: maven_build
  before_script:
    - mvn install:install-file -Dfile=target/ExpenseNest-0.0.1-SNAPSHOT.jar -DgroupId=expensenest -DartifactId=expensenest -Dversion=0.0.1-SNAPSHOT -Dpackaging=jar
  script:
    - mvn clean install


local_docker_build:
  image: docker:dind
  stage: docker_build
  tags:
    - group-03-runner
  script:
    - docker info
    - docker build -t $IMAGE_NAME .
    - docker save $IMAGE_NAME > $IMAGE_NAME.tar

deploy_to_local_docker:
  image: docker:dind
  stage: deploy
  tags:
    - group-03-runner
  script:
    - docker load < $IMAGE_NAME.tar
    - CONTAINER_ID=$(docker ps -q -a -f "expose=8080")
    - if [ -n "$CONTAINER_ID" ]; then docker stop $CONTAINER_ID && docker rm $CONTAINER_ID; fi
    - docker run -d -p 8080:8080 $IMAGE_NAME