# This is a sample .gitlab-ci.yml file for a GitLab CI/CD pipeline
# that uses stages, scripts with echo commands, and tags to associate
# a specific runner called 'jinal_dal_runner'.



stages:
  - build
  - test
  - deploy



# Define the build job
build_job:
  stage: build
  script:
    - echo "Building the code..."
    - echo "Build complete!"
  tags:
    - jinal_dal_runner



# Define the test job
test_job:
  stage: test
  script:
    - echo "Running tests..."
    - echo "Tests completed!"
  tags:
    - jinal_dal_runner



# Define the deployment job
deploy_job:
  stage: deploy
  script:
    - echo "Deploying to production..."
    - echo "Deployment complete!"
  tags:
    - jinal_dal_runner
